config/routes.rb
Rails.application.routes.draw do
  root to: 'episodes#index'
  get ':slug', to: 'episodes#show', constraints: { slug: /[0-9]{4}-[0-9]{2}-[0-9]{2}/ }, as: 'episode'

  scope format: 'xml' do
    get 'feed/sd.xml', to: 'feeds#sd', as: 'sd_feed'
    get 'feed/hd.xml', to: 'feeds#hd', as: 'hd_feed'
  end
end

app/models/episode.rb
require 'digest/sha1'
require 'mechanize'

class Episode < ActiveRecord::Base
  def self.create_with_vimeo_id(vimeo_id)
    raise 'Missing vimeo_id' unless vimeo_id
    episode = Episode.new(vimeo_id: vimeo_id)
    episode.update
    episode.save
    episode
  end

  def to_param
    slug
  end

  def subtitle
    description[0...255]
  end

  def description_html
    return nil unless description
    Twitter::Autolink.auto_link(description).gsub("\n", '<br>')
  end

  def video_url(type=:hd, secure=false)
    url = type == :sd ? sd_video_url : hd_video_url
    url = url.sub('https://', 'http://') unless secure
    signature = Digest::SHA1.hexdigest DOWNLOAD_SHARED_SECRET + url + slug + type.to_s
    "http://download.personalsam.com/video#{Addressable::URI.parse(url).extname}?url=#{CGI::escape url}&slug=#{slug}&type=#{type}&signature=#{signature}"
  end

  def content_type(type=:hd)
    type == :sd ? sd_content_type : hd_content_type
  end

  def file_size(type=:hd)
    type == :sd ? sd_file_size : hd_file_size
  end

  def poster_url(type=:hd, secure=false)
    url = type == :sd ? sd_poster_url : hd_poster_url
    url = url.sub('https://', 'http://') unless secure
    url
  end

  def extension(type=:hd)
    Addressable::URI.parse(video_url(type)).extname.sub('.', '')
  end

  def update
    response = Mechanize.new.get "https://api.vimeo.com/videos/#{vimeo_id}?access_token=#{VIMEO_ACCESS_TOKEN}"
    json = JSON(response.body)

    sd = json['files'].select { |f| f['quality'] == 'sd' }.first
    hd = json['files'].select { |f| f['quality'] == 'hd' }.first
    poster_id = (json['pictures']['sizes'].first)['link'].match(/https:\/\/i\.vimeocdn\.com\/video\/([0-9]+)_/)[1]
    published_at = DateTime.parse(json['created_time'])
    slug = json['name'].match(/([0-9]{4}-[0-9]{2}-[0-9]{2})/)[1]
    raise 'Missing slug' unless slug

    self.title = json['name']
    self.description = json['description']
    self.vimeo_id = vimeo_id.to_i
    self.duration = json['duration']
    self.published_at = published_at
    self.slug = slug
    self.sd_video_url = sd['link_secure']
    self.sd_content_type = sd['type']
    self.sd_file_size = Mechanize.new.head(sd['link_secure'])['content-length'].to_i
    self.sd_poster_url = "https://i.vimeocdn.com/video/#{poster_id}_640x360.jpg"
    self.hd_video_url = hd['link_secure']
    self.hd_content_type = hd['type']
    self.hd_file_size = Mechanize.new.head(hd['link_secure'])['content-length'].to_i
    self.hd_poster_url = "https://i.vimeocdn.com/video/#{poster_id}_1280x720.jpg"
    json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def index
    @episodes = Episode.order('published_at DESC')
  end

  def show
    not_found and return unless @episode = Episode.where(slug: params[:slug]).first
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :load_episodes

  def sd
    @type = :sd
    render template: 'feeds/podcast'
  end

  def hd
    @type = :hd
    render template: 'feeds/podcast'
  end

  private

  def load_episodes
    @episodes = Episode.order('published_at DESC')
  end
end

app/views/episodes/_episode.html.erb
<h3><%= link_to episode.title, episode_url(episode) %></h3>
<p><%= raw episode.description_html %></p>
<p><a href="http://vimeo.com/<%= episode.vimeo_id %>" rel="external nofollow">Watch on Vimeo</a> | Download: <a href="<%= episode.video_url :hd %>" download="<%= episode.slug %> HD.<%= episode.extension :hd %>">HD</a> <a href="<%= episode.video_url :sd %>" download="<%= episode.slug %> SD.<%= episode.extension :sd %>">SD</a></p>

app/views/episodes/index.html.erb
<p>Hi. Personal Sam is Sam Soffes' daily-ish video journal about with rambling about what he's working on, doing day to day, etc. It's more for archival purposes than anything.</p>
<p><mark>Subscribe on iTunes:</mark> <a href="https://itunes.apple.com/us/podcast/personal-sam-sd-video/id948185422" rel="external nofollow">SD</a> <a href="https://itunes.apple.com/us/podcast/personal-sam-hd-video/id948188434" rel="external nofollow">HD</a></p>
<p>Feed: <%= link_to 'SD', sd_feed_url %> <%= link_to 'HD', hd_feed_url %></p>
<p>Vimeo Channel: <a href="https://vimeo.com/channels/personalsam" rel="external nofollow">Personal Sam</a></p>

<hr>

<ol class="episodes">
<% @episodes.each do |episode| %>
  <li>
    <%= render episode %>
  </li>
<% end %>
</ol>

app/views/episodes/show.html.erb
<%= render @episode %>

<iframe src="//player.vimeo.com/video/<%= @episode.vimeo_id %>?title=0&amp;byline=0&amp;portrait=0" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

app/views/feeds/podcast.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
  <channel>
    <title>Personal Sam — <%= @type.to_s.upcase %> Video</title>
    <link>http://personalsam.com</link>
    <language>en-us</language>
    <copyright>&#169; <%= Time.now.year %> Sam Soffes</copyright>
    <itunes:subtitle>My daily-ish video journal</itunes:subtitle>
    <itunes:author>Sam Soffes</itunes:author>
    <itunes:summary>Personal Sam is Sam Soffes' daily-ish video journal about with rambling about what he's working on, doing day to day, etc. It's more for archival purposes than anything.</itunes:summary>
    <description>Personal Sam is Sam Soffes' daily-ish video journal about with rambling about what he's working on, doing day to day, etc. It's more for archival purposes than anything.</description>
    <itunes:owner>
      <itunes:name>Sam Soffes</itunes:name>
      <itunes:email>sam@soff.es</itunes:email>
    </itunes:owner>
    <itunes:image href="http://personalsam.s3.amazonaws.com/personal-sam-2048x2048.png" />
    <itunes:category text="Technology">
      <itunes:category text="Podcasting"/>
    </itunes:category>
    <itunes:explicit>clean</itunes:explicit>
    <atom:link href="http://personalsam.com/feed/<%= @type %>.xml" rel="self" type="application/rss+xml" />

    <% @episodes.each do |episode| %>
    <item>
      <title><%= episode.title %></title>
      <itunes:author>Sam Soffes</itunes:author>
      <% if episode.description %>
      <itunes:subtitle><%= episode.subtitle %></itunes:subtitle>
      <itunes:summary><![CDATA[<%= raw episode.description_html %>!]]></itunes:summary>
      <description><%= episode.description %></description>
      <% end %>
      <itunes:image href="<%= episode.poster_url(@type) %>" />
      <enclosure url="<%= episode.video_url(@type) %>" length="<%= episode.file_size(@type) %>" type="<%= episode.content_type(@type) %>" />
      <guid>http://personalsam.com/<%= episode.slug %>?<%= @type %></guid>
      <pubDate><%= episode.published_at.rfc2822 %></pubDate>
      <itunes:duration><%= episode.duration %></itunes:duration>
    </item>
    <% end %>
  </channel>
</rss>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Personal Sam</title>
  <link rel="stylesheet" type="text/css" href="//cloud.typography.com/619254/777982/css/fonts.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <link rel="alternate" type="application/atom+xml" href="<%= hd_feed_url %>">
  <link rel="alternate" type="application/atom+xml" href="<%= sd_feed_url %>">
  <% if Rails.env.production? && MIXPANEL_TOKEN %>
  <script>(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);mixpanel.init("<%= MIXPANEL_TOKEN %>");</script>
  <% end %>
</head>
<body>
  <header>
    <h1><a href="/" rel="home">Personal Sam</a></h1>
    <h2>My daily-ish video journal</h2>
  </header>
  <main>
    <%= yield %>
  </main>
<%= javascript_include_tag 'externals' %>
<% if Rails.env.production? && MIXPANEL_TOKEN %>
  <script>mixpanel.track('Page View',{'Title':document.title,'URL':window.location.pathname});</script>
<% end %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Personal Sam</h1>
<h2>My daily-ish video journal</h2>
<p>Hi. Personal Sam is Sam Soffes' daily-ish video journal about with rambling about what he's working on, doing day to day, etc. It's more for archival purposes than anything.</p>
<p><a href="https://vimeo.com/album/3129053" rel="external nofollow">Watch on Vimeo</a></p>
<p><mark>Subscribe:</mark> <%= link_to 'SD', sd_feed_url %> <%= link_to 'HD', hd_feed_url %></p>